!     Fortran-compatible stubs for fhn.c
!     These call the C implementations with proper Fortran calling convention

      SUBROUTINE FUNC(NDIM,U,ICP,PAR,IJAC,F,DFDU,DFDP)
      IMPLICIT NONE
      INTEGER NDIM,IJAC
      INTEGER ICP(*)
      DOUBLE PRECISION U(*),PAR(*)
      DOUBLE PRECISION F(*),DFDU(*),DFDP(*)
      INTEGER RESULT
      
      EXTERNAL FUNC_C
      INTEGER FUNC_C
      
      RESULT=FUNC_C(NDIM,U,ICP,PAR,IJAC,F,DFDU,DFDP)
      END


      SUBROUTINE STPNT(NDIM,U,PAR,T)
      IMPLICIT NONE
      INTEGER NDIM
      DOUBLE PRECISION U(*),PAR(*),T
      INTEGER RESULT
      
      EXTERNAL STPNT_C
      INTEGER STPNT_C
      
      RESULT=STPNT_C(NDIM,T,U,PAR)
      END


      SUBROUTINE PVLS(NDIM,U,PAR)
      IMPLICIT NONE
      INTEGER NDIM
      DOUBLE PRECISION U(*),PAR(*)
      INTEGER RESULT
      
      EXTERNAL PVLS_C
      INTEGER PVLS_C
      
      RESULT=PVLS_C(NDIM,U,PAR)
      END


      SUBROUTINE BCND(NDIM,PAR,ICP,NBC,U0,U1,FB,IJAC,DBC)
      IMPLICIT NONE
      INTEGER NDIM,NBC,IJAC
      INTEGER ICP(*)
      DOUBLE PRECISION PAR(*),U0(*),U1(*)
      DOUBLE PRECISION FB(*),DBC(*)
      INTEGER RESULT
      
      EXTERNAL BCND_C
      INTEGER BCND_C
      
      RESULT=BCND_C(NDIM,PAR,ICP,NBC,U0,U1,IJAC,FB,DBC)
      END


      SUBROUTINE ICND(NDIM,PAR,ICP,NINT,U,UOLD,UDOT,UPOLD,FI,IJAC,DINT)
      IMPLICIT NONE
      INTEGER NDIM,NINT,IJAC
      INTEGER ICP(*)
      DOUBLE PRECISION PAR(*),U(*),UOLD(*),UDOT(*),UPOLD(*)
      DOUBLE PRECISION FI(*),DINT(*)
      INTEGER RESULT
      
      EXTERNAL ICND_C
      INTEGER ICND_C
      
      RESULT=ICND_C(NDIM,PAR,ICP,NINT,U,UOLD,UDOT,UPOLD,IJAC,FI,DINT)
      END


      SUBROUTINE FOPT(NDIM,U,ICP,PAR,IJAC,FS,DFDU,DFDP)
      IMPLICIT NONE
      INTEGER NDIM,IJAC
      INTEGER ICP(*)
      DOUBLE PRECISION U(*),PAR(*)
      DOUBLE PRECISION FS(*),DFDU(*),DFDP(*)
      INTEGER RESULT
      
      EXTERNAL FOPT_C
      INTEGER FOPT_C
      
      RESULT=FOPT_C(NDIM,U,ICP,PAR,IJAC,FS,DFDU,DFDP)
      END

